version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: whos-on-my-network
    container_name: whos-on-my-network
    environment:
      - DATABASE_PATH=/data/database.sqlite
      - PORT=9000
      - SCANNER=default
      - NETWORK_ID=192.168.1.0/24
    volumes:
      - ./database.sqlite:/data/database.sqlite
    network_mode: host
    command: ["start"]
  watch:
    build:
      context: .
      dockerfile: Dockerfile
    image: whos-on-my-network
    container_name: whos-on-my-network-watch
    environment:
      - DATABASE_PATH=/data/database.sqlite
      - SCANNER=default
      - NETWORK_ID=192.168.1.0/24
    volumes:
      - ./database.sqlite:/data/database.sqlite
    network_mode: host
    command: ["watch"]
