version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: whos-on-my-network
    container_name: whos-on-my-network
    environment:
      - DATABASE_PATH=/data/database.sqlite
      - SCANNER=default
    ports:
      - "8081:3000"
    volumes:
      - ./database.sqlite:/data/database.sqlite
    command: ["start"]
  watch:
    build:
      context: .
      dockerfile: Dockerfile
    image: whos-on-my-network
    container_name: whos-on-my-network-watch
    environment:
      - DATABASE_PATH=/data/database.sqlite
      - SCANNER=default
    volumes:
      - ./database.sqlite:/data/database.sqlite
    command: ["watch"]
